### ISSUE TITLE
Get rid of kleisli gem in Dry::Data::SumType

### ISSUE THREAD

**Issue by kirs** [dryrb/dry-types#12]
`Dry::Data::SumType` uses `kliesli` gem, which overrides basic Ruby object (`Object` and `Kernel`) and `method_added`.

It also somehow conflicts with Rails and ActiveSupport: https://gist.github.com/kirs/6bdcb0ed284d94c76a5f

**Comment by solnic** [comment]
Hey @txus is this something that can be fixed? I didn't know about the method_added tweaks :/

**Comment by timriley** [comment]
Looks like we can pretty easily pull out the part of Kleisli with the `method_added` behaviour. I've just done it in txus/kleisli#17 – @kirs, if you want to have a go at using my fork of kleisli, and seeing whether it fixes the problem, that'd be great!

**Comment by kirs** [comment]
@timriley thanks! It works! :rocket:

**Comment by solnic** [comment]
Is this still a problem?

**Comment by kirs** [comment]
Nope it's solved.
