### ISSUE TITLE
"symbolized" Hash schema only accepts string keys input

### ISSUE THREAD

**Issue by jeromegn** [dryrb/dry-types#20]
While working on a more tolerant `Dry::Data::Struct`, I experimented with both `Dry::Data::Type::Hash#symbolized` and `#schema`. Turns out the `symbolized` schema will only apply string keys.

```ruby
hash = Dry::Data::Type::Hash.symbolized(name: Types::String)

hash['name' => 'hello'] # => {:name => 'hello'}
hash[name: 'hello'] # => {}
```

I understand the documentation is pretty clear about the purpose of symbolized schemas:

> Symbolized hash will turn **string key names** into symbols

but I was wondering if it might be nice to just `#to_sym` whatever key passed in (`String`, `Symbol`) to both the schema creation and type instantiation so something like that would work:

```ruby
hash = Dry::Data::Type::Hash.symbolized(
  name: Types::String,
  'age' => Types::Integer
)

hash['name' => 'hello', age: 10] # => {:name => 'hello', :age => 10}
```

I'd be happy to work on the implementation if that's a desirable feature.

**Comment by solnic** [comment]
Could you tell me what kind of use cases you had where key types were mixed?

**Comment by solnic** [comment]
I made `symbolized` hash accept already-symbolized hashes, they also respect default values now.
