### ISSUE TITLE
Allow defaults to be set on on sum types

### ISSUE THREAD

**Issue by timriley** [dryrb/dry-types#23]
If I have a type like this:

```ruby
Types::Form::Bool.default(false)
```

I'll get this error:

```
NoMethodError: undefined method `default' for #<Dry::Data::SumType:0x007f805b9a51b8>
```

Should it be possible to allow default values for sum types? Seems like in this case at least it'd make sense.

Let me know what you think and I'd be happy to take a stab at implementing this.

Thanks!

**Comment by solnic** [comment]
Thanks Tim. I plan a small refactoring before fixing this.
