### ISSUE TITLE
Error requiring 'dry-types': undefined method `visit_type?'

### ISSUE THREAD

**Issue by jonahx** [dryrb/dry-types#33]
Hi Piotr,

Since the gem isn't yet available using `gem install dry-types`, I cloned the master branch of the git repo, built it locally, and installed from that.  After doing a `require 'dry-types'`, however, I get this error:

```
/Users/jg/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/dry-logic-0.1.4/lib/dry/logic/rule_compiler.rb:18:in `visit': undefined method `visit_type?' for #<Dry::Logic::RuleCompiler:0x007f91552edef0> (N
oMethodError)
```
Should I be using another method for installation?

**Comment by solnic** [comment]
hey Jonah, it's a bad moment to live on the edge, the 3 gems (types, logic, validation) are going through refactorings, please wait for the releases, ETA is end of the month.

**Comment by jonahx** [comment]
thanks for the update

**Comment by solnic** [comment]
Closing this one as refactorings are over and all 3 gems can be used from master, releases are "around the corner" ;)
