### ISSUE TITLE
Enum for integer attributes

### ISSUE THREAD

**Issue by flash-gordon** [dryrb/dry-types#34]
Hello,

I was a little bit confused with next scenario:
```ruby
2.3.0 :001 > require 'dry-data'
 => true
2.3.0 :002 > billing_period = Dry::Data['int'].enum(1, 3, 6, 12)
 => #<Dry::Data::Enum:0x007fe1fc85de88 @type=#<Dry::Data::Constrained:0x007fe1fc85ded8 @type=#<Dry::Data::Type constructor=#<Method: Dry::Data::Type.constructor> options={:primitive=>Integer}>, @options={:rule=>#<Dry::Logic::Rule::Value name=Integer predicate=#<Dry::Logic::Predicate id=:inclusion?>>}, @rule=#<Dry::Logic::Rule::Value name=Integer predicate=#<Dry::Logic::Predicate id=:inclusion?>>>, @options={:values=>[1, 3, 6, 12]}, @values=[1, 3, 6, 12]>
2.3.0 :003 > billing_period[3]
 => 12
2.3.0 :004 >
```

Here you can see that due to [special Fixnum processing](https://github.com/dryrb/dry-types/blob/a7892c5f53d5f067822310e68b6150ba1dcadef7/lib/dry/types/enum.rb#L18) actual billing period was treated as an array index. That led me to some strange troubles. My spec builds model then persists it (occasionally with wrong value 12 instead of 3). After that when I try to fetch that record from DB the spec fails with an error "nil violates constraints" because it reads 12 and then tries to construct a value by calling PeriodType[12].

It is quite confusing, isn't it? What do you think? :)

P.S. Piotr I want to thank you very much for all that cool stuff. Great work!

Nikita

**Comment by solnic** [comment]
Hey Nikita, thanks for this gentle bug report, I will fix it in the next version :)
