### ISSUE TITLE
Shouldn't Kleisli::Maybe::None be understood as nil in some cases?

### ISSUE THREAD

**Issue by davidpelaez** [dryrb/dry-types#35]
If I create a Struct type and then take the resulting object and convert it to hash again and pass it to the exact same Struct, shouldn't it be valid? Maybe it's very obvious why they shouldn't, but given my very limited experience with very strict functional code it made sense to open the issue.

Consider this:

```ruby
class MyStruct < Dry::Data::Struct
  attribute :a,  Types::String
  attribute :b,  Types::String.optional
end

x = MyStruct.new a: 2, b: nil 
#=> {
#  :a => 2,
#  :b => None
#}

y = MyStruct.new x.to_h
#=> {
#  :a => 2,
#  :b => Some(None)  <----- Shouldn't this simply be None?
#}
```

I would expect the resulting hash for `y` to be equivalent to `x` because the meaning on `None` should mean the same as `nil` in this case. I understand how they are different because `nil` is not a "value" but a "wrapper" of no value. However shouldn't the coercion of no value be the same for nil?

This project and related ones like ROM have moved my code to a new level. I appreciate the effort. It's still quite different for me and I'm still getting used to it, so I'd appreciate any assistance in understanding wether this is a bug or not. ;)

**Comment by solnic** [comment]
Thanks for reporting this. I'd say it's a bug. I'll address this in the current refactoring.

**Comment by davidpelaez** [comment]
I had a problem that led me to this and it's basically that I cannot make the output of a type be a valid input for itself given this situation. This had the issue that I would take an object and coerce it at the entry of an HTTP call and then would pass that data to a series of steps that in the end get coerced again with the exact same coercer at the exit point. This is used for consistency so that we guarantee the format in both directions.

I solved the problem by defining a new type `Nothing` that can be `nil` or `None`:

```ruby
require 'kleisli'
module Types
  class Nothing
    extend Dry::Data::TypeBuilder
    class << self
      def call(input)
        input.nil? ? Kleisli::Maybe::None.new : input
      end

      def try(input)
        call(input)
      end

      def valid?(input)
        #binding.pry
        input.nil? || input.is_a?(Kleisli::Maybe::None)
      end

      alias_method :[], :call
    end
  end
end

Dry::Data.register "types.nothing", Types::Nothing

class Kleisli::Maybe::None
  def to_json
    nil.to_json
  end
end

class Kleisli::Maybe::Some
  def to_json
    value.to_json
  end
end
```

Then instead of using `#optional` I created sum types by hand, e.g.: `OptionalString = Nothing | String` and this solved all my issues. I wanted to share this because maybe it can help the conversation by showing why another type besides `Nil` could be needed.

**Comment by davidpelaez** [comment]
I'm not sure this is the best way to create custom typed, but it's what I managed to figure out by reading the code since there were no docs about building custom types/coercers without recurring to sums or fmap.

**Comment by solnic** [comment]
The only way to add custom types is to use public type definition API. It's a new thing, ie:

``` ruby
class Email
end

# shortcut which assumes `Email.method(:new)` is the constructor
Dry::Types.register_class(Email)

# this expands to:
Dry::Types::Definition.new(Email).constructor(Email.method(:new))
```

**Comment by davidpelaez** [comment]
@solnic thanks for the PR and for the help with custom types!
